name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major
      release_type:
        description: 'Release type (release, alpha, beta, rc)'
        required: true
        default: 'alpha'
        type: 'choice'
        options:
          - release
          - alpha
          - beta
          - rc

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [10.0.0-beta.1]
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Authenticating with GitHub Packages
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Bumping the version for release
        if: github.event.inputs.release_type == 'release'
        run: pnpm version-bump:${{ github.event.inputs.version_bump_type }}
      - name: Bumping the version for others
        if: github.event.inputs.release_type != 'release'
        run: pnpm version-bump:${{ github.event.inputs.version_bump_type }}:${{ github.event.inputs.release_type }}
      - name: Publishing the library package
        run: |
          pnpm build:prod
          pnpm publish:${{ github.event.inputs.release_type }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Output package details
        run: cat package.json
